import type { PluginContracts } from './types';
import { contractsSchemaId, contractsVersion } from './version';

/**
 * Release Manager plugin contracts manifest
 * Level 2: Contracts типизация с as const для извлечения типов
 */
export const pluginContractsManifest = {
  schema: contractsSchemaId,
  pluginId: '@kb-labs/release-manager',
  contractsVersion,
  artifacts: {
    'release.plan.json': {
      id: 'release.plan.json',
      kind: 'json',
      description: 'Serialized release plan generated by `kb release plan`.',
      pathPattern: '.kb/release/plan.json',
      mediaType: 'application/json',
    },
    'release.report.json': {
      id: 'release.report.json',
      kind: 'json',
      description: 'Execution report emitted by `kb release run`.',
      pathPattern: '.kb/release/report.json',
      mediaType: 'application/json',
    },
    'release.changelog.md': {
      id: 'release.changelog.md',
      kind: 'markdown',
      description: 'Workspace changelog output produced during release.',
      pathPattern: '.kb/release/changelog.md',
      mediaType: 'text/markdown',
    },
  },
  commands: {
    'release:plan': {
      id: 'release:plan',
      description: 'Analyze changes and prepare release plan',
      examples: [
        'kb release plan',
        'kb release plan --scope packages/*',
        'kb release plan --bump minor',
        'kb release plan --json',
      ],
    },
    'release:run': {
      id: 'release:run',
      description: 'Execute release process (plan, check, publish)',
      examples: [
        'kb release run',
        'kb release run --scope packages/*',
        'kb release run --dry-run',
        'kb release run --strict',
      ],
    },
    'release:rollback': {
      id: 'release:rollback',
      description: 'Rollback last release',
      examples: ['kb release rollback'],
    },
    'release:report': {
      id: 'release:report',
      description: 'Show release report',
      examples: ['kb release report'],
    },
    'release:changelog': {
      id: 'release:changelog',
      description: 'Generate changelog',
      examples: ['kb release changelog'],
    },
    'release:preview': {
      id: 'release:preview',
      description: 'Preview release plan without executing',
      examples: [
        'kb release preview',
        'kb release preview --scope packages/*',
      ],
    },
    'release:verify': {
      id: 'release:verify',
      description: 'Verify release readiness (checks, tests, etc.)',
      examples: [
        'kb release verify',
        'kb release verify --scope packages/*',
      ],
    },
  },
} as const satisfies PluginContracts;

// Извлекаем типы для использования в других местах
export type PluginArtifactIds = keyof typeof pluginContractsManifest.artifacts;
export type PluginCommandIds = keyof typeof pluginContractsManifest.commands;

