import { access, mkdir, writeFile } from 'node:fs/promises';
import { constants as fsConstants } from 'node:fs';
import { dirname, join } from 'node:path';

type SetupContext = {
  cwd?: string;
  runtime?: {
    log?: (
      level: 'debug' | 'info' | 'warn' | 'error',
      message: string,
      meta?: Record<string, unknown>
    ) => void;
  };
};

const RELEASE_DIRS = ['plans', 'reports', 'backups'];

export async function run(ctx: SetupContext = {}) {
  const cwd = ctx.cwd ?? process.cwd();
  const releaseDir = join(cwd, '.kb', 'release');
  const created: string[] = [];

  await mkdir(releaseDir, { recursive: true });

  for (const dir of RELEASE_DIRS) {
    const target = join(releaseDir, dir);
    await mkdir(target, { recursive: true });
    created.push(target);
  }

  await ensureFile(
    join(releaseDir, '.gitignore'),
    ['# Release artifacts', 'plans/', 'reports/', 'backups/', '*.json', '*.md', ''].join('\n')
  );

  await ensureFile(
    join(releaseDir, 'README.md'),
    [
      '# KB Labs Release workspace',
      '',
      'This directory stores release plans, reports, and backups generated by `kb release ...` commands.',
      '',
      'Contents are environment-specific and should not be committed unless you intentionally share release evidence.',
      '',
    ].join('\n')
  );

  ctx.runtime?.log?.('info', 'Release setup completed', { cwd, created });

  return {
    ok: true,
    releaseDir,
    created,
  };
}

async function ensureFile(path: string, contents: string) {
  try {
    await access(path, fsConstants.F_OK);
  } catch {
    await mkdir(dirname(path), { recursive: true });
    await writeFile(path, contents, 'utf-8');
  }
}

