packages:
  - packages/*
  - ../../infra/kb-labs-devkit
  - ../../infra/kb-labs-plugin/apps/*
  - ../../infra/kb-labs-plugin/packages/*
  - ../../platform/kb-labs-sdk/packages/*
  - ../../platform/kb-labs-studio/apps/*
  - ../../platform/kb-labs-studio/packages/*
