schemaVersion: "1.0"
sync:
  enabled: true
products:
  release:
    registry: "https://registry.npmjs.org"
    strategy: semver
    bump: auto
    strict: true
    verify:
      - audit
      - build
      - tests
    publish:
      npm: true
      github: false
    rollback:
      enabled: true
      maxHistory: 5
    output:
      json: true
      md: true
      text: true

