import { access, mkdir, writeFile } from 'node:fs/promises';
import { constants as fsConstants } from 'node:fs';
import { dirname, join } from 'node:path';

type SetupContext = {
  cwd?: string;
  runtime?: {
    log?: (
      level: 'debug' | 'info' | 'warn' | 'error',
      message: string,
      meta?: Record<string, unknown>
    ) => void;
  };
};

const RELEASE_DIRS = ['plans', 'reports', 'backups'];

export async function run(ctx: SetupContext = {}) {
  const cwd = ctx.cwd ?? process.cwd();
  const releaseDir = join(cwd, '.kb', 'release');
  const created: string[] = [];

  await mkdir(releaseDir, { recursive: true });

  for (const dir of RELEASE_DIRS) {
    const target = join(releaseDir, dir);
    await mkdir(target, { recursive: true });
    created.push(target);
  }

  await ensureFile(
    join(releaseDir, '.gitignore'),
    ['# Release artifacts', 'plans/', 'reports/', 'backups/', '*.json', '*.md', ''].join('\n')
  );

  await ensureFile(
    join(releaseDir, 'README.md'),
    [
      '# KB Labs Release workspace',
      '',
      'This directory stores release plans, reports, and backups generated by `kb release ...` commands.',
      '',
      'Contents are environment-specific and should not be committed unless you intentionally share release evidence.',
      '',
    ].join('\n')
  );

  // Generate example release.config.ts with checks
  await ensureFile(
    join(releaseDir, 'release.config.example.ts'),
    [
      '/**',
      ' * Example Release Manager Configuration',
      ' * Copy to release.config.ts and customize',
      ' */',
      '',
      'export default {',
      '  checks: [',
      '    {',
      '      id: \'build\',',
      '      command: \'pnpm\',',
      '      args: [\'build\'],',
      '      parser: \'exitcode\',',
      '      timeoutMs: 300000, // 5 minutes',
      '    },',
      '    {',
      '      id: \'tests\',',
      '      command: \'pnpm\',',
      '      args: [\'test\'],',
      '      parser: \'exitcode\',',
      '      timeoutMs: 120000, // 2 minutes',
      '      optional: true, // Don\'t fail release if tests fail',
      '    },',
      '    // Custom check with JSON output',
      '    // {',
      '    //   id: \'devlink\',',
      '    //   command: \'kb\',',
      '    //   args: [\'devlink\', \'check\', \'--json\'],',
      '    //   parser: \'json\',',
      '    // },',
      '    // Custom check with function parser',
      '    // {',
      '    //   id: \'lint\',',
      '    //   command: \'pnpm\',',
      '    //   args: [\'lint\'],',
      '    //   parser: (stdout, stderr, exitCode) => exitCode === 0 && !stdout.includes(\'error\'),',
      '    // },',
      '  ],',
      '};',
      '',
    ].join('\n')
  );

  ctx.runtime?.log?.('info', 'Release setup completed', { cwd, created });

  return {
    ok: true,
    releaseDir,
    created,
    configDefaults: {
      workspace: {
        type: 'pnpm',
        root: '.',
      },
      git: {},
      changelog: {
        locale: 'en',
      },
    },
  };
}

async function ensureFile(path: string, contents: string) {
  try {
    await access(path, fsConstants.F_OK);
  } catch {
    await mkdir(dirname(path), { recursive: true });
    await writeFile(path, contents, 'utf-8');
  }
}

