import type { PluginContextV3 } from '@kb-labs/sdk';

const RELEASE_DIRS = ['plans', 'reports', 'backups'];

export async function run(ctx: PluginContextV3) {
  const cwd = ctx.cwd;
  const releaseDir = ctx.runtime.fs.join(cwd, '.kb', 'release');
  const created: string[] = [];

  await ctx.runtime.fs.mkdir(releaseDir, { recursive: true });

  for (const dir of RELEASE_DIRS) {
    const target = ctx.runtime.fs.join(releaseDir, dir);
    await ctx.runtime.fs.mkdir(target, { recursive: true });
    created.push(target);
  }

  await ensureFile(
    ctx,
    ctx.runtime.fs.join(releaseDir, '.gitignore'),
    ['# Release artifacts', 'plans/', 'reports/', 'backups/', '*.json', '*.md', ''].join('\n')
  );

  await ensureFile(
    ctx,
    ctx.runtime.fs.join(releaseDir, 'README.md'),
    [
      '# KB Labs Release workspace',
      '',
      'This directory stores release plans, reports, and backups generated by `kb release ...` commands.',
      '',
      'Contents are environment-specific and should not be committed unless you intentionally share release evidence.',
      '',
    ].join('\n')
  );

  // Generate example release.config.ts with checks
  await ensureFile(
    ctx,
    ctx.runtime.fs.join(releaseDir, 'release.config.example.ts'),
    [
      '/**',
      ' * Example Release Manager Configuration',
      ' * Copy to release.config.ts and customize',
      ' */',
      '',
      'export default {',
      '  checks: [',
      '    {',
      '      id: \'build\',',
      '      command: \'pnpm\',',
      '      args: [\'build\'],',
      '      parser: \'exitcode\',',
      '      timeoutMs: 300000, // 5 minutes',
      '    },',
      '    {',
      '      id: \'tests\',',
      '      command: \'pnpm\',',
      '      args: [\'test\'],',
      '      parser: \'exitcode\',',
      '      timeoutMs: 120000, // 2 minutes',
      '      optional: true, // Don\'t fail release if tests fail',
      '    },',
      '    // Custom check with JSON output',
      '    // {',
      '    //   id: \'devlink\',',
      '    //   command: \'kb\',',
      '    //   args: [\'devlink\', \'check\', \'--json\'],',
      '    //   parser: \'json\',',
      '    // },',
      '    // Custom check with function parser',
      '    // {',
      '    //   id: \'lint\',',
      '    //   command: \'pnpm\',',
      '    //   args: [\'lint\'],',
      '    //   parser: (stdout, stderr, exitCode) => exitCode === 0 && !stdout.includes(\'error\'),',
      '    // },',
      '  ],',
      '};',
      '',
    ].join('\n')
  );

  ctx.platform.logger.info('Release setup completed', { cwd, created });

  return {
    ok: true,
    releaseDir,
    created,
    configDefaults: {
      workspace: {
        type: 'pnpm',
        root: '.',
      },
      git: {},
      changelog: {
        locale: 'en',
      },
    },
  };
}

async function ensureFile(ctx: PluginContextV3, path: string, contents: string) {
  const exists = await ctx.runtime.fs.exists(path);
  if (!exists) {
    const dir = ctx.runtime.fs.dirname(path);
    await ctx.runtime.fs.mkdir(dir, { recursive: true });
    await ctx.runtime.fs.writeFile(path, contents, { encoding: 'utf-8' });
  }
}

